# Generated by Django 4.2.26 on 2025-11-14 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_classroom"),
        ("accounts", "0002_user_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                help_text="The classroom this student belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="game.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy: The teacher this student belongs to (use classroom instead)",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
