# Generated by Django 4.2.26 on 2025-11-08 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BucketProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.IntegerField(db_index=True)),
                (
                    "words_mastered",
                    models.IntegerField(
                        default=0, help_text="Words correctly spelled in this bucket"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
            ],
            options={"ordering": ["bucket"],},
        ),
        migrations.CreateModel(
            name="GameConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "words_to_complete_bucket",
                    models.IntegerField(
                        default=200,
                        help_text="Number of words to master before progressing to next difficulty",
                    ),
                ),
                (
                    "recycling_distance",
                    models.IntegerField(
                        default=100,
                        help_text="Incorrect words will reappear within this many words",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("words_correct", models.IntegerField(default=0)),
                ("words_attempted", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["-started_at"],},
        ),
        migrations.CreateModel(
            name="StudentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_bucket", models.IntegerField(default=3)),
                ("total_words_correct", models.IntegerField(default=0)),
                ("total_attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Student progress",},
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "difficulty_bucket",
                    models.IntegerField(
                        db_index=True, help_text="Difficulty level based on word length"
                    ),
                ),
                ("word_length", models.IntegerField()),
            ],
            options={"ordering": ["difficulty_bucket", "text"],},
        ),
        migrations.CreateModel(
            name="WordQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(help_text="Position in queue (lower = sooner)"),
                ),
                (
                    "times_failed",
                    models.IntegerField(
                        default=0,
                        help_text="How many times this word was answered incorrectly",
                    ),
                ),
                ("is_mastered", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.word"
                    ),
                ),
            ],
            options={"ordering": ["position"],},
        ),
        migrations.CreateModel(
            name="WordAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_spelling", models.CharField(max_length=100)),
                ("is_correct", models.BooleanField()),
                (
                    "attempt_number",
                    models.IntegerField(
                        default=1,
                        help_text="How many times this word has been attempted",
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="game.gamesession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.word"
                    ),
                ),
            ],
            options={"ordering": ["-attempted_at"],},
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["difficulty_bucket", "text"],
                name="game_word_difficu_e4ef2b_idx",
            ),
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gameconfiguration",
            name="teacher",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_config",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bucketprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bucket_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wordqueue", unique_together={("student", "word")},
        ),
        migrations.AlterUniqueTogether(
            name="bucketprogress", unique_together={("student", "bucket")},
        ),
    ]
