# Generated by Django 4.2.26 on 2025-11-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameconfiguration",
            name="default_starting_bucket",
            field=models.IntegerField(
                default=3,
                help_text="Default starting difficulty bucket for new students (word length)",
            ),
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="custom_starting_bucket",
            field=models.IntegerField(
                blank=True,
                help_text="Custom starting bucket set by teacher (overrides default)",
                null=True,
            ),
        ),
    ]
