# Generated by Django 4.2.26 on 2025-11-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprogress", name="custom_starting_bucket",
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="total_points_earned",
            field=models.IntegerField(
                default=0,
                help_text="Total points earned from correct words (points = word length)",
            ),
        ),
        migrations.AlterField(
            model_name="studentprogress",
            name="current_bucket",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
