# Generated by Django 4.2.26 on 2025-11-17 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0004_remove_studentprogress_custom_starting_bucket_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BucketLadder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this bucket ladder (e.g., 'Grade Levels', 'Difficulty Progression', 'Animal Themes')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this bucket ladder",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bucket_ladders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["teacher", "name"],
                "unique_together": {("teacher", "name")},
            },
        ),
        migrations.CreateModel(
            name="CustomBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this bucket (e.g., 'Easy Words', 'Grade 3', 'Animals')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this bucket"
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="Order in the ladder (lower = earlier)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_buckets",
                        to="game.bucketladder",
                    ),
                ),
            ],
            options={
                "ordering": ["ladder", "position"],
                "unique_together": {("ladder", "position")},
            },
        ),
        migrations.AlterModelOptions(
            name="bucketprogress", options={"ordering": ["bucket", "custom_bucket"]},
        ),
        migrations.AlterUniqueTogether(name="bucketprogress", unique_together=set(),),
        migrations.AlterUniqueTogether(name="wordqueue", unique_together=set(),),
        migrations.AddField(
            model_name="classroom",
            name="default_starting_bucket",
            field=models.IntegerField(
                default=3,
                help_text="Default starting bucket for new students (only used when bucket_ladder is null)",
            ),
        ),
        migrations.AlterField(
            model_name="bucketprogress",
            name="bucket",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordattempt",
            name="word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.word",
            ),
        ),
        migrations.AlterField(
            model_name="wordqueue",
            name="word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.word",
            ),
        ),
        migrations.CreateModel(
            name="CustomWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        db_index=True,
                        help_text="The word text (letters and hyphens only)",
                        max_length=100,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_words",
                        to="game.custombucket",
                    ),
                ),
            ],
            options={
                "ordering": ["bucket", "text"],
                "unique_together": {("bucket", "text")},
            },
        ),
        migrations.AddField(
            model_name="bucketprogress",
            name="custom_bucket",
            field=models.ForeignKey(
                blank=True,
                help_text="Custom bucket (only used when classroom uses custom ladder)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_records",
                to="game.custombucket",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="bucket_ladder",
            field=models.ForeignKey(
                blank=True,
                help_text="Custom bucket ladder for this classroom. If null, uses default system buckets.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="game.bucketladder",
            ),
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="custom_bucket",
            field=models.ForeignKey(
                blank=True,
                help_text="Current custom bucket (only used when classroom uses custom ladder)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_progresses",
                to="game.custombucket",
            ),
        ),
        migrations.AddField(
            model_name="wordattempt",
            name="custom_word",
            field=models.ForeignKey(
                blank=True,
                help_text="Custom word (only used when classroom uses custom ladder)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="game.customword",
            ),
        ),
        migrations.AddField(
            model_name="wordqueue",
            name="custom_word",
            field=models.ForeignKey(
                blank=True,
                help_text="Custom word (only used when classroom uses custom ladder)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_entries",
                to="game.customword",
            ),
        ),
    ]
